//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObuvApp_Kumyshbaeva.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> IdPoint { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> IdOrderStatus { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Point Point { get; set; }
        public virtual USer USer { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
