//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObuvApp_Kumyshbaeva.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public Nullable<int> IdManufacturer { get; set; }
        public Nullable<int> IdProductCategory { get; set; }
        public Nullable<double> ActiveDiscount { get; set; }
        public Nullable<int> WorkshopCount { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public double? NewPrice {
            get {
                if (ActiveDiscount.HasValue && ActiveDiscount.Value > 0 && Price.HasValue)
                    return Price - Price * ActiveDiscount / 100;
                else
                    return Price;
            }
        }
        public bool HasDiscount => ActiveDiscount.HasValue && ActiveDiscount > 0;

        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
