//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObuvApp_Kumyshbaeva.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.USer = new HashSet<USer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<USer> USer { get; set; }
    }
}
