//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObuvApp_Kumyshbaeva.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class USer
    {
        public USer()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdRole { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual Role Role { get; set; }
    }
}
